### PR TITLE
images

### PR DESCRIPTION
**Pull request by seyfuddin**
images

### CODE REVIEW

**Comment by af1f1ah** [comment]
good

**Comment by af1f1ah** [comment]
idk why its not working

**Comment by seyfuddin** [comment]
oh i think i know why

**Comment by af1f1ah** [comment]
why

**Comment by seyfuddin** [comment]
never mind i amm ganna ask the teacher

**Comment by af1f1ah** [comment]
seyfuddin go on snap pls

**Comment by seyfuddin** [comment]
why

**Comment by af1f1ah** [comment]
cuz i texted y its impotent its abt this

**Comment by af1f1ah** [comment]
also whats our team name

**Comment by seyfuddin** [comment]
team coders

**Review by TRXPZ-FURKAN — APPROVED** [review]

**Comment by af1f1ah** [comment]
why isnt it working for me

**Comment by seyfuddin** [comment]
wait how did furkan approve it

**Review by af1f1ah — APPROVED** [review]

**Comment by TRXPZ-FURKAN** [comment]
it is knida easy though

**Pull request merged**
